### ISSUE TITLE
Missing constraints for W formulation

### ISSUE THREAD

**Issue by kibaekkim** [Argonne-National-Laboratory/NetDecOPF.jl#5]
@wzhangw I wonder if we need constraints `w[i] == vr[i]^2 + vi[i]^2`. Also see https://github.com/Argonne-National-Laboratory/NetDecOPF.jl/blob/weiqi_local/src/prob_ext.jl#L16-L19

**Comment by wzhangw** [comment]
Right, we should need the w squared constraints in W formulation.
